[tool.black]
# Line length 96 is simply because I like base 12. 96/12 = 8, another nice number for computing.
line-length = 96
target-version = ['py311']
# Use single quotes, can format with ruff.
skip-string-normalization = true

[tool.ruff]
# Config: https://beta.ruff.rs/docs/configuration/
# and https://beta.ruff.rs/docs/settings/
line-length = 96
target-version = 'py311'
output-format = 'grouped'
extend-include = ["*.ipynb"]

# Rules: https://beta.ruff.rs/docs/rules/
# Always include 'Q' for single quote usage with Black
select = ['ALL']

# F722 is incompatible with nptyping.
# F722: Checks for forward annotations that include invalid syntax.
# Ignore FIX002 (T002 before Ruff 0.0.272) to allow TODO comments
# Ignore ANN101 and ANN102 since we use typing.Self in python 3.11
# Rest are from https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
ignore = [
  'F722',
  'FIX002',
  'ANN101',
  'ANN102',
  'W191',
  'E111',
  'E114',
  'E117',
  'D206',
  'D300',
  'Q000',
  'Q001',
  'Q002',
  'Q003',
  'COM812',
  'COM819',
  'ISC001',
  'ISC002',
  'D416',
]

  [tool.ruff.format]
  quote-style = 'single'

  [tool.ruff.isort]
  combine-as-imports = true

  [tool.ruff.pydocstyle]
  convention = 'google'

  [tool.ruff.flake8-quotes]
  inline-quotes = 'single'
  multiline-quotes = 'double'
  docstring-quotes = 'double'

[tool.pyright]
strictListInference = true
strictDictionaryInference = true
strictSetInference = true
